"""
User Models Module for Omnisage Medical Record Aggregator.

This module defines the SQLAlchemy database models representing users, authentication
credentials, and security metadata for shared record sessions.
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime, Boolean, JSON
from sqlalchemy.orm import relationship
from backend.database import Base


class User(Base):
    """
    SQLAlchemy model representing a patient/user account.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    full_name = Column(String, nullable=True)
    hashed_password = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    records = relationship("MedicalRecord", back_populates="owner", cascade="all, delete-orphan")


class SharedLink(Base):
    """
    SQLAlchemy model representing an expiring consent sharing link generated by the user.
    """
    __tablename__ = "shared_links"

    id = Column(String, primary_key=True, index=True)  # Secure UUID string
    creator_id = Column(Integer, nullable=False)
    record_ids = Column(JSON, nullable=False)  # List of record IDs accessible through this link
    expiry_time = Column(DateTime, nullable=False)
    passcode_hash = Column(String, nullable=True)  # Hashed passcode for security (optional)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # No ORM relationship back to User to keep this model self-contained and avoid mapper ordering issues
